<?php
include_once "DataProvider.php";
include_once "ContainerContent.php";
include_once "Department.php";
include_once "ContainerTree.php";
include_once "AbstractTree.php";
include_once "DepartmentTree.php";
use task_report\DataProvider;
use task_report\ContainerContent;
use task_report\Department;
use task_report\ContainerTree;
use task_report\AbstractTree;
use task_report\DepartmentTree;
//new DataProvider("select ID, NAME, IBLOCK_SECTION_ID from b_iblock_section where IBLOCK_ID=5");
$request = "select ID, NAME, IBLOCK_SECTION_ID from b_iblock_section where IBLOCK_ID=5";
$tree = new DepartmentTree($request);
echo $tree->getTreeSelectForHTML();
//$tree->treeReduce(function($a,$b){return $a." ".$b." ";});
//$str = $tree->toString();
//print_r($str);
//var_dump($tree);
//print_r((new DataProvider("select ID, NAME, IBLOCK_SECTION_ID from b_iblock_section where IBLOCK_ID=5"))->getData());